package database;

public enum DBAnswer {
    OBJECTNOTEXIST,
    DUPLICATESDETECTED,
    ISNTMAX,
    PERMISSIONDENIED,
    SUCCESSFUL,
    SQLPROBLEM,
    EMPTYCOLLECTION,
    ALREADYREGISTERED,
    NOTMATCH
}